[build]
  command = "npm run build"  # El comando para construir tu aplicación
  publish = "dist"           # La carpeta que contiene los archivos estáticos para implementar

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Plugin específico para Next.js
